grammar Lang;
NUMBER:[0-9]+('.'[0-9]*)?|'.'[0-9]+;
WHITESPACE:[ \n\r\t]+ ->skip;
ADD:'+';
SUB:'-';
MUL:'*';
DIV:'/';
VAR:[A-Za-z][A-Za-z0-9]*;
FUNC_DEC:'func';
function:FUNC_DEC(name=VAR)'('var1=VAR'):'(st+=statement)+'return '(ret=expr)';';
expr:left=add(op+=('+'|'-')right+=add)*;
add:left=mul(op+=('*'|'/'|':=')right+=mul)*;
mul:(neg='-')?(num = NUMBER|'('expr')'|var=VAR);
assignment:(var=VAR)op=':='(ex=expr);
statement:(assign = assignment)';';
program:(f+=function)*(st+=statement);
