grammar Lang;
NUMBER:[0-9]+('.'[0-9]*)?|'.'[0-9]+;
WHITESPACE:[ \n\r\t]+ ->skip;
ADD:'+';
SUB:'-';
MUL:'*';
DIV:'/';
expr:left=add(op+=('+'|'-')right+=add)*;
add:left=mul(op+=('*'|'/')right+=mul)*;
mul:(neg='-')?(num = NUMBER|'('expr')');
